db:
    core:
        driverManager: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/databus_core?useSSL=false&useUnicode=true&characterEncoding=utf-8&useServerPrepStmts=false&rewriteBatchedStatements=true&autoReconnect=true
        username: dave
        password: 123123
    sys:
        driverManager: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/databus_sys?useSSL=false&useUnicode=true&characterEncoding=utf-8&useServerPrepStmts=false&rewriteBatchedStatements=true&autoReconnect=true
        username: dave
        password: 123123

admin:
    appkey: XYZ123
    skey: XYZ123

redis:
    host: localhost
    port: 6379
    db:
        recordApi: 10
        accessCache: 1

server:
    port: 8888

default:
    defaultTakes: 10
    maxPOSTLength: 4096